### ISSUE TITLE
Add version tag

### ISSUE THREAD

**Issue by psychowood** [puneethrai/angular-long-press#1]
Hi,
Would you mind tagging the current release with a version, to allow cleaner integration with bower?

Thanks

**Comment by puneethrai** [comment]
Thank you for pointing it out, I've tagged the branch to 0.2.0 

> bower info angular-long-press
> bower not-cached    https://github.com/puneethrai/angular-long-press.git#*
> bower resolve       https://github.com/puneethrai/angular-long-press.git#*
> bower checkout      angular-long-press#0.2.0
> bower resolved      https://github.com/puneethrai/angular-long-press.git#0.2.0

{
  name: 'angular-long-press',
  version: '0.2.0',
  main: [
    './dist/angular-long-press.js'
  ],
  authors: [
    'Puneeth Rai npuneethrai@yahoo.co.in'
  ],
  repository: {
    type: 'git',
    url: 'git://github.com/puneethrai/angular-long-press.git'
  },
  description: 'An angular.js long press directive for both desktop and mobile',

  moduleType: [
    'globals'
  ],
  keywords: [
    'angular',
    'angular.js',
    'long',
    'press',
    'touch',
    'touchend',
    'desktop',
    'mobile'
  ],
  license: 'MIT',
  ignore: [
    '*_/._',
    'node_modules',
    'bower_components',
    'test',
    'tests'
  ],
  dependencies: {
    angular: '1.x'
  },
  devDependencies: {},
  resolutions: {
    angular: '1.x'
  },
  homepage: 'https://github.com/puneethrai/angular-long-press'
}

Available versions:
- 0.2.0
  You can request info for a specific version with 'bower info angular-long-press#
  <version>'
