### ISSUE TITLE
Misalignment with Angular Material mdMenu

### ISSUE THREAD

**Issue by simonered** [puneethrai/angular-long-press#10]
When used with Angular Material **Menu** directive it causes the menu-content alignment to fail.
I think it's something related with event and I'm trying to investigate further.

Here is a [pen](https://codepen.io/simonered/pen/ZrLbaY).

**Comment by simonered** [comment]
Found the reason: mdMenu is expecting that its trigger button has an _ng-click_ attribute set. So just defining it (as blank, if not needed) solves the case.

I've updated the [pen](https://codepen.io/simonered/pen/ZrLbaY).

Hope it helps.

**Comment by puneethrai** [comment]
cool, thanks for the update.
