### ISSUE TITLE
We should disable long press while scrolling

### ISSUE THREAD

**Issue by grrrian** [puneethrai/angular-long-press#3]
To address this we can add the following:

```
                    // ...
                    var touchStartY;
                    var touchStartX;
                    var MAX_DELTA = 15;

                    // ...

                    $elm.bind('touchmove', onMove);

                    // in onEnter(), add:
                    touchStartY = _.get(evt, 'touches[0].screenY');
                    touchStartX = _.get(evt, 'touches[0].screenX');

                    // ...

                    function onMove(evt) {
                        var yPosition = _.get(evt, 'touches[0].screenY');
                        var xPosition = _.get(evt, 'touches[0].screenX');

                        // If we scrolled, prevent long presses
                        if (!_.isUndefined(touchStartY) && !_.isUndefined(touchStartX) &&
                            (Math.abs(yPosition - touchStartY) > MAX_DELTA) || Math.abs(xPosition - touchStartX) > MAX_DELTA) {
                            $timeout.cancel(timer);
                        }

                    }
```

The 15px delta is to help with "fat fingers". Very slight scrolling is probably unintentional.

**Comment by puneethrai** [comment]
We can put it as config param and default it prevent long press while scrolling.

Option Name: prevent-onscrolling: Boolean value to prevent long press when user is scrolling . Default is true

**Comment by puneethrai** [comment]
Done. Provided in 0.3.0
Thank you for the suggestion and code snippet

**Comment by mkurzweil** [comment]
Hi,

I have following error when I set `prevent-onscrolling="true"`:

> angular-long-press.js:84 Uncaught TypeError: Cannot read property '0' of undefined
> onMove    @   angular-long-press.js:84
> dispatch  @   jquery.js:4435
> r.handle  @   jquery.js:4121

I'm using angular 1.3.15
Thanks for any suggestions

**Comment by puneethrai** [comment]
Hi @mkurzweil I haven't tested the library with Angular 1.3 version. Let me test in that version and also can you please do let me know which device you used to test. I also see that you are using JQuery, please do mention version number of it.

**Comment by mkurzweil** [comment]
@puneethrai thanks for quick reply
- jquery 2.1.4
- android 4.x and 5.x

**Comment by puneethrai** [comment]
@mkurzweil I tested in android 6.x device, I see no issue. Since I couldn't find any android device with 4 or 5, if possible can you share the screenshot/object key and values of "evt" object at line 84. if there is key by name touches please give the values inside it.

**Comment by mkurzweil** [comment]
@puneethrai I hope this helps:

<img width="331" alt="bildschirmfoto 2016-08-12 um 11 26 46" src="https://cloud.githubusercontent.com/assets/9111128/17618429/0fcc0d8a-6080-11e6-9d85-c814b10dfac0.png">

**Comment by puneethrai** [comment]
@mkurzweil Thanks for the screenshot.... This is not part of standard [Touch Move](https://developer.mozilla.org/en-US/docs/Web/Events/touchmove) . But nonetheless let us target these devices as well. Just curious to know, can you tell me device make and browser.

**Comment by mkurzweil** [comment]
@puneethrai ok nice to know.
The above screenshot is from chrome 52.0.2743.116

And this one is from my android device 5.0.2:
<img width="380" alt="bildschirmfoto 2016-08-12 um 11 52 03" src="https://cloud.githubusercontent.com/assets/9111128/17619041/3b74bb28-6083-11e6-9387-8784aa6d4f28.png">

**Comment by puneethrai** [comment]
Issue: Exception occurred when TouchMove is triggered
Observation: For certain devices TouchMove event is triggered without touches object in root level instead it is present inside originalEvent
Target fix version: 0.3.2

**Comment by puneethrai** [comment]
@mkurzweil I did some research looks like when JQuery is used, it replaces event and encapsulate it in its object by renaming event to originalEvent.

**Comment by puneethrai** [comment]
Fixed. Please use v0.3.2

**Comment by puneethrai** [comment]
@mkurzweil Thank you for letting me know this issue.
