### ISSUE TITLE
Unknown provider?

### ISSUE THREAD

**Issue by jsiegmund** [puneethrai/angular-long-press#6]
I'm trying to use this directive inside of my Cordova Angular app, but it's failing and I'm not sure why. Angular error says: 

`Unknown provider: nProvider <- n <- onLongPressDirective`

I have verified: 
- The source js is loaded 
- My app has the 'pr.longpress' module inserted, not seeing any errors there
- The directive code should be ok: 
  `<button on-long-press="vm.toggle(log)">test</button>`

But still the above error. What am I missing here?

**Comment by jsiegmund** [comment]
Very odd, when I manually change the module name from pr.longpress to my own module, I first get a dependency error stating that it can't find the pr.longpress module (which tells me it's trying to load it). Then when I remove the dependency from my app, this fixes the error. There's now no 'unknown provider' error any more, but it doesn't seem to be working either. 

Maybe a little background around my use case: I've got a md-list with md-list-item elements in it, I want to be able to long-press those in order to select an entire item (or multiple at once).

**Comment by puneethrai** [comment]
I got your issue...For now please don't use angular-long-press.min.js use angular-long-press.js .
I Haven't properly injected my dependence in minified file. Will release a patch soon.

**Comment by puneethrai** [comment]
Fixed. Please use 0.3.1.
Thank you for letting me know this issue.
