### ISSUE TITLE
Can you use it with Google Maps?

### ISSUE THREAD

**Issue by degaray** [puneethrai/angular-long-press#9]
I am using this with a ng-map instance, but it does not send the event.

**Comment by puneethrai** [comment]
Can you give me a snippet how you are trying to use it with ng-map

**Comment by tabman83** [comment]
just wrap ng-map in a div and apply long-press to that

**Comment by puneethrai** [comment]
looks like on mouse up/down event is being consumed by underneath div which not getting bubbled up and there by our event listener not able to catch it. Need to do some experiment

**Comment by puneethrai** [comment]
Closing this issue as there is nothing much can be done if the event doesn't get bubbled up. We can consider @tabman83 suggestion to make it work. Feel free to reopen this bug if the solution provided is not working.
